--- #YAML:1.0
name: Parse-CPAN-Authors
version: 2.25
author:
  - Leon Brocard <acme@astray.com>
abstract: Parse 01mailrc.txt.gz
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
