--- #YAML:1.0
name: Parse-CPAN-Authors
version: 2.20
author:
  - Leon Brocard <acme@astray.com>
abstract: Parse 01mailrc.txt.gz
license: perl
requires:
  Class::Accessor::Fast: 0
  Mail::Address: 0
  Test::More: 0
provides:
  Parse::CPAN::Authors:
    file: lib/Parse/CPAN/Authors.pm
    version: 2.20
  Parse::CPAN::Authors::Author:
    file: lib/Parse/CPAN/Authors/Author.pm
    version: 2.12
generated_by: Module::Build version 0.24
